# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-10 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
